# dnf module disable mysql -y 

# /etc/yum.repos.d/mysql.repo

# [mysql]
# name=MySQL 5.7 Community Server
# baseurl=http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
# enabled=1
# gpgcheck=0

# yum install mysql-community-server -y
# systemctl enable mysqld
# systemctl start mysqld  
# mysql_secure_installation --set-root-pass RoboShop@1
# mysql -uroot -pRoboShop@1

- name: Copy Mysql Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
   
- name: Disable Mysql version 8
  ansible.builtin.shell: dnf module disable mysql -y
  
- name: Install mysql-5.7
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed
    
- name: Start MySQL services
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes
    
- name: Set Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.password', region='us-east-1') }}
  ignore_errors: yes
 