# - name: test
#   debug:
#     msg: test

- name: Update Prometheus Configuration
  ansible.builtin.template:
  src: prometheus.yml
  dest: /opt/prometheus/prrometheus.yml
  
- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted