# id roboshop &>>${log_file}
# if [ $? -ne 0 ]; then
# useradd roboshop &>>${log_file}
# fi
# status_check $?

# print_head "creating Apllication Directory"
# if [ ! -d /app ]; then
# mkdir /app &>>${log_file}
# fi
# status_check $?

# print_head "cleaning old files"
# rm -rf /app/* &>>${log_file}
# status_check $?

# print_head "Downloading App Content zip file"
# curl -L -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>${log_file}
# status_check $?

# print_head "Changing Directory"
# cd /app &>>${log_file}
# status_check $?

# print_head "Extracting App content"
# unzip /tmp/${component}.zip &>>${log_file}
# status_check $?
# # }

- name: Create Application User
  ansible.builtin.user:
    name: roboshop
    
- name: Delete old App Directory
  ansible.builtin.file:
    name: /app
    state: absent
    
- name: Create App Directory
  ansible.builtin.file:
    name: /app
    state: directory
    
- name: Download and Extract {{ component }} App Files
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app 
    remote_src: yes