# chema_setup() { 
#  if [ "${schema_type}" == "mongo" ]; then
#  print_head "Copy mongodb repo files"
#  cp ${code_dir}/config/mongodb.repo /etc/yum.repos.d/mongo.repo &>>${log_file}
#  status_check $?

#  print_head "Install mongodb client"
#  yum install mongodb-org-shell -y &>>${log_file}
#  status_check $?

#  print_head "Load schema to mongodb"
#  mongo --host mongodb-dev.devops36.shop </app/schema/${component}.js &>>${log_file}
#  status_check $?
#  elif [ "${schema_type}" == "mysql" ]; then
 
#  print_head "Install MySql Client"
#  yum install mysql -y &>>${log_file}
#  status_check $?
 
#  print_head "Applying password to MySql password and Loading Schema"
#  mysql -h mysql-dev.devops36.shop -uroot -p${mysql_root_password} < /app/schema/shipping.sql &>>${log_file}
#  status_check $?
#  fi
# }
#mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pRoboShop@1 < /app/schema/shipping.sql 

- name: MongoDB Schema
  when: schema_type == "mongo"
  block:
    - name: Setup MongoDB repo Files
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
      
    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
         
    - name: Load Schema
      ansible.builtin.shell: mongo --host mongodb-dev.devops36.shop </app/schema/{{component}}.js
       
- name: MySql Schema
  when: schema_type == "mysql"
  block:
    - name: Install MySql Client
      ansible.builtin.yum:
        name: mysql
        state: installed
         
    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.devops36.shop -uroot -pRoboShop@1 < /app/schema/{{component}}.sql 
        
       

