- name: MongoDB Schema
  when: schema_type == "mongo"
  block:
    - name: Setup MongoDB repo Files
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
      
    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
         
    - name: Load Schema
      ansible.builtin.shell: mongo --host mongodb-dev.devops36.shop </app/schema/{{component}}.js
       
- name: MySql Schema
  when: schema_type == "mysql"
  block:
    - name: Install MySql Client
      ansible.builtin.yum:
        name: mysql
        state: installed
         
    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.devops36.shop -uroot -pRoboShop@1 < /app/schema/{{component}}.sql
      
      
      
     
        
       

