groups:
- name: roboshop-service-alerts
  rules:
  {% for component in components %}

  - alert: ServiceDown Alert-{{ component }} Service
    expr: node_systemd_unit_state{exported_name="{{ component }}.service", state="active"}
    for: 30s
    labels:
      severity: critical
      appName: {{ component }}
    annotations:
      summary: Service Down on Server - Service Name - {{ component }}.service
{% endfor %}
