groups:
- name: roboshop-service-alerts
  rules:
  {% for component in components %}

  - alert: ServiceDown Alert-{{ item }} Service
    expr: node_systemd_unit_state{exported_name="{{ item }}.service", state="active"}
    for: 30s
    labels:
      severity: critical
      appName: {{ item }}
    annotations:
      summary: Service Down on Server - Service Name - {{ item }}.service
{% endfor %}
